from .ttm import TTM
from .wttm import WTTM
from .kd import DistillKL
from .at import Attention
from .FitNet import HintLoss
from .rkd import RKDLoss
from .ofd import OFD
from .reviewkd import ReviewKD
from .simkd import SimKD
from .cat_kd import CAT_KD
from .dkd import DKD
from .mlkd import MLKD
from .crd import CRDLoss
from .itrd import ITLoss
from .dist import DIST